server:
  port: 10000
  tomcat:
    connection-timeout: 20000
spring:
  application:
    name: GatherProduct
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.26.84.226/gather_mall_goods?characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql1553381095
    hikari:
      read-only: false
      connection-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10
  cloud:
    nacos:
      discovery:
        server-addr: 120.26.84.226:8848





mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.gathermall.product: debug